version: '3'
services:
  bingo-nginx:
    container_name: "bingo-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - bingo-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  bingo-app:
    container_name: "bingo-app"
    build:
      context: ./docker/php
    depends_on:
      - bingo-mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  bingo-mysql:
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "bingo-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bingo
      - MYSQL_USER=root
    ports:
      - "4306:3306"

  bingo-redis:
    image: redis:alpine
    container_name: "bingo-redis"
    ports:
      - 16379:6379
